import { notFound } from "next/navigation";
import { AdminPage } from "@/components/admin/admin-page";
import { AdminCard } from "@/components/admin/admin-widgets";
import { ContentManager } from "@/components/admin/content-manager";
import { getCmsResource, serializeDocument } from "@/lib/server/cms-resources";
import { getDb } from "@/lib/server/mongodb";
import { getAdminMediaOptions } from "@/lib/server/admin-data";
import { SuccessStoriesManager } from "@/components/admin/success-stories-manager";
import { BtsProjectsManager } from "@/components/admin/bts-projects-manager";
export const dynamic = "force-dynamic";
const allowed = ["categories", "success-stories", "bts-projects", "galleries", "statistics", "benefits"];
export default async function ResourcePage({ params }: { params: Promise<{ resource: string }> }) { const resource = (await params).resource; if (!allowed.includes(resource)) notFound(); const config = getCmsResource(resource); if (!config) notFound(); const [rows, images, videos] = await Promise.all([(await getDb()).collection(config.collection).find({}).sort({ createdAt: -1, sortOrder: 1 }).limit(200).toArray(), getAdminMediaOptions("image"), getAdminMediaOptions("video")]); const serialized = serializeDocument(rows) as Array<{ _id: string; title?: string; name?: string; slug: string; description?: string; status?: string; sortOrder?: number; isActive?: boolean; mediaIds?: string[]; data?: Record<string, unknown>; type?: string }>; if (resource === "success-stories") return <AdminPage eyebrow="Success stories" title="Story management" intro="Create, update, publish, and add cover images or playable videos to each story."><AdminCard title="Stories" eyebrow={`${rows.length} records`}><SuccessStoriesManager initialRows={serialized} images={images} videos={videos} /></AdminCard></AdminPage>; if (resource === "bts-projects") return <AdminPage eyebrow="Behind the scenes" title="BTS management" intro="Create, update, publish, and add a cover image with an optional playable YouTube or CDN video."><AdminCard title="BTS projects" eyebrow={`${rows.length} records`}><BtsProjectsManager initialRows={serialized} images={images} videos={videos} /></AdminCard></AdminPage>; const media = resource === "galleries" ? [...images, ...videos] : images; return <AdminPage eyebrow="Content" title={resource.replaceAll("-", " ")} intro="Create drafts, attach uploaded media, edit every field, and control what is published."><AdminCard title="Content records" eyebrow={`${rows.length} records`}><ContentManager resource={resource} initialRows={serialized} media={media} /></AdminCard></AdminPage>; }
