import type { Metadata } from "next";
import { SectionHeading } from "@/components/section-heading";
export const metadata: Metadata = { title: "Privacy & Cookies Policy", description: "How MeroStream collects, uses, and protects personal information and uses cookies." };
const sections = [
  ["1. What Information We Collect", ["Information you provide voluntarily: When you contact us, sign up for a newsletter, or submit an inquiry, we may collect your name, email address, and any other information you choose to share.", "Information collected automatically: As you browse meroestream.com, our systems may collect technical data including your IP address, browser type, device information, and browsing activity."]],
  ["2. How We Use Your Data", ["We use information to respond to inquiries, talent submissions, and feedback; analyze usage trends and improve our platform; and maintain the security of our platform, users, and intellectual property.", "We do not sell your personal data. We are building a community, not a data-mining operation."]],
  ["3. Cookies & Tracking Technologies", ["Essential cookies are necessary for security, navigation, and core website functionality and cannot be disabled through our site.", "Performance and analytics cookies help us understand how visitors interact with our content. Functionality cookies remember preferences such as language or region.", "You can control or disable cookies through your browser settings. Blocking all cookies may prevent some website features from working as intended."]],
  ["4. Your Rights", ["Depending on your location, you may have rights to access your data, correct inaccuracies, request deletion subject to legal obligations, or object to how we process your data. Contact us to exercise these rights."]],
  ["5. Third-Party Links", ["Our website may link to external sites such as festival websites and filmmaker portfolios. We are not responsible for their privacy practices or content, and encourage you to review their policies."]],
  ["6. Updates to This Policy", ["As MeroStream grows, this policy may change. Updates will be posted on this page and significant changes may also be communicated to registered users."]],
  ["7. Contact Us", ["Questions about privacy or personal information can be sent to admin@meroesteam.com with the subject line “Privacy Inquiry – MeroStream.”"]],
] as const;
export default function PrivacyPolicyPage() { return <section className="bg-obsidian pt-36 md:pt-44"><article className="container-shell max-w-4xl pb-20 md:pb-28"><SectionHeading eyebrow="Legal" title="Privacy & Cookies Policy" intro="Last updated: 29 July 2026" /><p className="mt-10 leading-8 text-papyrus/72">We believe in the power of stories and the integrity of the people who tell them. This policy explains what information we collect, why we collect it, and how we protect your privacy while you use MeroStream.</p><div className="mt-12 grid gap-10">{sections.map(([heading, paragraphs]) => <section key={heading}><h2 className="font-serif text-3xl text-papyrus">{heading}</h2><div className="mt-4 grid gap-4">{paragraphs.map((paragraph) => <p key={paragraph} className="leading-8 text-papyrus/68">{paragraph}</p>)}</div></section>)}</div></article></section>; }
