"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";

type MediaOption = { id: string; title: string; mediaType: "image" | "video"; source?: string };
type Row = { _id: string; title?: string; name?: string; slug: string; description?: string; status?: string; sortOrder?: number; isActive?: boolean; mediaIds?: string[]; data?: Record<string, unknown>; type?: string };
export function ContentManager({ resource, initialRows, media }: { resource: string; initialRows: Row[]; media: MediaOption[] }) {
  const router = useRouter(); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false);
  const isCategory = resource === "categories";
  function payload(formData: FormData, row?: Row) {
    const title = String(formData.get("title") ?? "");
    if (isCategory) return { name: title, slug: formData.get("slug"), type: formData.get("type"), description: formData.get("description"), status: row?.status ?? "draft", sortOrder: Number(formData.get("sortOrder") ?? 0), isActive: true };
    const data: Record<string, unknown> = { ...(row?.data ?? {}) };
    if (resource === "success-stories") { data.role = formData.get("role"); data.projects = String(formData.get("projects") ?? "").split("\n").map((v) => v.trim()).filter(Boolean); }
    if (resource === "bts-projects") data.captions = String(formData.get("captions") ?? "").split("\n").map((v) => v.trim());
    if (resource === "galleries") { data.city = formData.get("city"); data.country = formData.get("country"); data.dates = formData.get("dates"); data.status = formData.get("publicStatus"); }
    if (resource === "statistics") { data.value = Number(formData.get("value") ?? 0); data.label = title; }
    if (resource === "benefits") data.label = formData.get("label");
    return { title, slug: formData.get("slug"), description: formData.get("description"), mediaIds: formData.getAll("mediaIds").map(String), data, status: row?.status ?? "draft", sortOrder: Number(formData.get("sortOrder") ?? 0), isActive: true };
  }
  async function create(formData: FormData) {
    setBusy(true); const body = payload(formData);
    const response = await fetch(`/api/admin/content/${resource}`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); const result = await response.json(); setBusy(false); setMessage(response.ok ? "Draft created." : result.error ?? "Unable to create."); if (response.ok) router.refresh();
  }
  async function update(row: Row, formData: FormData) { setBusy(true); const response = await fetch(`/api/admin/content/${resource}/${row._id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload(formData, row)) }); const result = await response.json(); setBusy(false); setMessage(response.ok ? "Changes saved." : result.error ?? "Unable to save."); if (response.ok) router.refresh(); }
  async function publish(id: string, published: boolean) { setBusy(true); const response = await fetch(`/api/admin/content/${resource}/${id}/publish`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ published }) }); const result = await response.json(); setBusy(false); setMessage(response.ok ? "Publishing updated." : result.error ?? "Unable to publish."); if (response.ok) router.refresh(); }
  const field = "min-h-11 border border-papyrus/15 bg-obsidian px-4 text-papyrus";
  function fields(row?: Row) { const data = row?.data ?? {}; return <><div className="grid gap-4 md:grid-cols-2"><input required name="title" defaultValue={row?.title ?? row?.name} placeholder={isCategory ? "Category name" : "Title"} className={field} /><input required name="slug" defaultValue={row?.slug} pattern="[a-z0-9]+(?:-[a-z0-9]+)*" placeholder="url-safe-slug" className={field} /></div>{isCategory ? <select name="type" defaultValue={row?.type ?? "film"} className={field}><option value="film">Film</option><option value="documentary">Documentary</option><option value="theatre">Theatre</option><option value="music">Music</option><option value="other">Other</option></select> : null}<textarea name="description" defaultValue={row?.description} rows={3} placeholder="Description / biography / details" className={`${field} py-3`} />{resource === "success-stories" ? <><input name="role" defaultValue={String(data.role ?? "")} placeholder="Role" className={field} /><textarea name="projects" defaultValue={Array.isArray(data.projects) ? data.projects.join("\n") : ""} placeholder="Associated projects, one per line" className={`${field} py-3`} /></> : null}{resource === "bts-projects" ? <textarea name="captions" defaultValue={Array.isArray(data.captions) ? data.captions.join("\n") : ""} placeholder="Image captions, one per selected image" className={`${field} py-3`} /> : null}{resource === "galleries" ? <div className="grid gap-4 md:grid-cols-2"><input name="city" defaultValue={String(data.city ?? "")} placeholder="City" className={field} /><input name="country" defaultValue={String(data.country ?? "")} placeholder="Country" className={field} /><input name="dates" defaultValue={String(data.dates ?? "")} placeholder="Dates" className={field} /><input name="publicStatus" defaultValue={String(data.status ?? "Upcoming")} placeholder="Upcoming / Live / Streaming" className={field} /></div> : null}{resource === "statistics" ? <input name="value" type="number" defaultValue={Number(data.value ?? 0)} placeholder="Numeric value" className={field} /> : null}{resource === "benefits" ? <input name="label" defaultValue={String(data.label ?? "")} placeholder="Card label, e.g. I" className={field} /> : null}{!isCategory && resource !== "statistics" && resource !== "benefits" ? <select multiple name="mediaIds" defaultValue={row?.mediaIds ?? []} className={`${field} min-h-36 py-2`}>{media.map((item) => <option key={item.id} value={item.id}>{item.title} ({item.mediaType})</option>)}</select> : null}<input name="sortOrder" type="number" defaultValue={row?.sortOrder ?? 0} placeholder="Order" className={`${field} w-32`} /></>; }
  return <div className="grid gap-7"><form action={create} className="grid gap-4 border border-papyrus/10 p-5">{fields()}<button disabled={busy} className="w-fit rounded-full bg-sahel px-5 py-3 text-xs font-bold uppercase text-obsidian">Create draft</button></form>{message ? <p className="text-sm text-sahel">{message}</p> : null}<div className="grid gap-3">{initialRows.map((row) => <details key={row._id} className="border border-papyrus/10 p-4"><summary className="cursor-pointer"><span className="text-papyrus">{row.title ?? row.name}</span><span className="ml-3 text-xs text-papyrus/45">/{row.slug} · {row.status ?? "draft"}</span></summary><form action={(data) => update(row, data)} className="mt-5 grid gap-4">{fields(row)}<div className="flex gap-3"><button disabled={busy} className="rounded-full bg-sahel px-4 py-2 text-xs font-bold uppercase text-obsidian">Save</button><button type="button" disabled={busy} onClick={() => publish(row._id, row.status !== "published")} className="rounded-full border border-papyrus/20 px-4 py-2 text-xs uppercase">{row.status === "published" ? "Unpublish" : "Publish"}</button></div></form></details>)}</div></div>;
}
