"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { InlineStoryMediaManager } from "@/components/admin/inline-story-media-manager";
import { MediaUploadForm } from "@/components/admin/media-upload-form";
import { YoutubeVideoForm } from "@/components/admin/youtube-video-form";

type Media = { id: string; title: string; publicUrl?: string; source: string };
type Story = { _id: string; title?: string; slug: string; description?: string; status?: string; sortOrder?: number; isActive?: boolean; mediaIds?: string[]; data?: Record<string, unknown> };

function slugify(value: string) { return value.toLowerCase().trim().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "") || `story-${Date.now()}`; }

function StoryFields({ story }: { story?: Story }) {
  const data = story?.data ?? {};
  const initialProjects = Array.isArray(data.projects) && data.projects.length ? data.projects.map(String) : [""];
  const [projects, setProjects] = useState(initialProjects);
  const field = "min-h-11 border border-papyrus/15 bg-obsidian px-4 text-papyrus";
  return <>
    <div className="grid gap-4 md:grid-cols-2"><label className="grid gap-2"><span className="label">Name</span><input required name="title" defaultValue={story?.title ?? ""} placeholder="Korede Olayinka" className={field} /></label><label className="grid gap-2"><span className="label">Role</span><input required name="role" defaultValue={String(data.role ?? "")} placeholder="Actor, theatre performer, and story collaborator" className={field} /></label></div>
    <label className="grid gap-2"><span className="label">Story / biography</span><textarea required name="description" rows={6} defaultValue={story?.description ?? ""} className={`${field} py-3`} /></label>
    <fieldset className="grid gap-3 border border-papyrus/10 p-4"><legend className="label px-2">Associated projects</legend>{projects.map((project, index) => <div key={index} className="flex gap-2"><input name="projects" defaultValue={project} placeholder="The Iron River" className={`${field} flex-1`} /><button type="button" onClick={() => setProjects((items) => items.filter((_, itemIndex) => itemIndex !== index))} className="border border-papyrus/15 px-3 text-xs uppercase text-red-200">Remove</button></div>)}<button type="button" onClick={() => setProjects((items) => [...items, ""])} className="w-fit rounded-full border border-sahel/50 px-4 py-2 text-xs uppercase text-sahel">+ Add project</button></fieldset>
  </>;
}

export function SuccessStoriesManager({ initialRows, images, videos }: { initialRows: Story[]; images: Media[]; videos: Media[] }) {
  const router = useRouter(); const [busy, setBusy] = useState(false); const [message, setMessage] = useState("");
  const [newCoverId, setNewCoverId] = useState(""); const [newVideoId, setNewVideoId] = useState(""); const [newVideoMode, setNewVideoMode] = useState<"r2" | "youtube">("r2");
  function payload(formData: FormData, story?: Story, media?: { coverId: string; videoId: string }) {
    const title = String(formData.get("title") ?? "").trim();
    const coverMediaId = media?.coverId ?? String(formData.get("coverMediaId") ?? story?.data?.coverMediaId ?? story?.mediaIds?.[0] ?? ""); const videoMediaId = media?.videoId ?? String(formData.get("videoMediaId") ?? story?.data?.videoMediaId ?? "");
    if (videoMediaId && !coverMediaId) throw new Error("Choose a cover photo before adding a video.");
    return { title, slug: story?.slug || slugify(title), description: String(formData.get("description") ?? ""), mediaIds: [coverMediaId, videoMediaId].filter(Boolean), data: { ...(story?.data ?? {}), role: String(formData.get("role") ?? ""), projects: formData.getAll("projects").map(String).map((item) => item.trim()).filter(Boolean), coverMediaId: coverMediaId || null, videoMediaId: videoMediaId || null }, status: story?.status ?? "draft", sortOrder: Number(story?.sortOrder ?? 0), isActive: story?.isActive !== false };
  }
  async function save(formData: FormData, story?: Story, media?: { coverId: string; videoId: string }, publishAfterCreate = false) { setBusy(true); setMessage(""); try { const response = await fetch(story ? `/api/admin/content/success-stories/${story._id}` : "/api/admin/content/success-stories", { method: story ? "PATCH" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload(formData, story, media)) }); const result = await response.json(); if (!response.ok) throw new Error(result.error ?? "Unable to save story."); if (publishAfterCreate && result.data?._id) { const published = await fetch(`/api/admin/content/success-stories/${result.data._id}/publish`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ published: true }) }); if (!published.ok) throw new Error("Story was created, but could not be published."); setNewCoverId(""); setNewVideoId(""); } setMessage(story ? "Story updated." : publishAfterCreate ? "New story created and published." : "New story created as a draft."); router.refresh(); } catch (error) { setMessage(error instanceof Error ? error.message : "Unable to save story."); } finally { setBusy(false); } }
  async function publish(story: Story) { setBusy(true); const response = await fetch(`/api/admin/content/success-stories/${story._id}/publish`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ published: story.status !== "published" }) }); const result = await response.json(); setMessage(response.ok ? story.status === "published" ? "Story returned to draft." : "Story published." : result.error ?? "Unable to publish story."); setBusy(false); if (response.ok) router.refresh(); }
  async function remove(story: Story) { if (!window.confirm(`Delete ${story.title}?`)) return; setBusy(true); const response = await fetch(`/api/admin/content/success-stories/${story._id}`, { method: "DELETE" }); const result = await response.json(); setMessage(response.ok ? "Story deleted." : result.error ?? "Unable to delete story."); setBusy(false); if (response.ok) router.refresh(); }
  return <div className="grid gap-7">
    <details open className="border border-sahel/35 bg-sahel/[0.035] p-5"><summary className="cursor-pointer font-serif text-2xl text-papyrus">+ Add new story</summary><div className="mt-5 grid gap-5"><div className="grid gap-4 border border-papyrus/10 p-4"><p className="label">Cover photo</p><MediaUploadForm defaultMediaType="image" lockMediaType onUploaded={async (id) => { setNewCoverId(id); setMessage("Cover uploaded. Add the story content and optional video, then publish."); }} />{newCoverId ? <p className="text-sm text-emerald-200">Cover ready.</p> : null}</div>{newCoverId ? <div className="grid gap-4 border border-papyrus/10 p-4"><p className="label">Optional playable video</p><div className="flex gap-2"><button type="button" onClick={() => setNewVideoMode("r2")} className={`rounded-full border px-4 py-2 text-xs uppercase ${newVideoMode === "r2" ? "border-sahel bg-sahel text-obsidian" : "border-papyrus/15"}`}>CDN / R2</button><button type="button" onClick={() => setNewVideoMode("youtube")} className={`rounded-full border px-4 py-2 text-xs uppercase ${newVideoMode === "youtube" ? "border-sahel bg-sahel text-obsidian" : "border-papyrus/15"}`}>YouTube</button></div>{newVideoMode === "r2" ? <MediaUploadForm defaultMediaType="video" lockMediaType onUploaded={async (id) => { setNewVideoId(id); setMessage("R2 video ready."); }} /> : <YoutubeVideoForm onCreated={async (id) => { setNewVideoId(id); setMessage("YouTube video ready."); }} />}{newVideoId ? <p className="text-sm text-emerald-200">Video ready.</p> : null}</div> : <p className="text-sm text-amber-200">Upload the cover photo to enable video options.</p>}<form action={(data) => save(data, undefined, { coverId: newCoverId, videoId: newVideoId }, true)} className="grid gap-5 border-t border-papyrus/10 pt-5"><StoryFields /><button disabled={busy || !newCoverId} className="w-fit rounded-full bg-sahel px-5 py-3 text-xs font-bold uppercase text-obsidian disabled:opacity-50">Create and publish story</button></form></div></details>
    {message ? <p className="border border-papyrus/10 p-4 text-sm text-sahel">{message}</p> : null}
    <div className="grid gap-4">{initialRows.map((story) => <details key={story._id} className="border border-papyrus/10 p-5"><summary className="cursor-pointer"><span className="font-serif text-2xl text-papyrus">{story.title}</span><span className="ml-3 text-xs uppercase text-papyrus/45">{story.status ?? "draft"}</span></summary><div className="mt-5 grid gap-5"><InlineStoryMediaManager story={story} images={images} videos={videos} /><form action={(data) => save(data, story)} className="grid gap-5"><StoryFields story={story} /><div className="flex flex-wrap gap-3"><button disabled={busy} className="rounded-full bg-sahel px-4 py-2 text-xs font-bold uppercase text-obsidian">Save changes</button><button type="button" disabled={busy} onClick={() => publish(story)} className="rounded-full border border-papyrus/20 px-4 py-2 text-xs uppercase">{story.status === "published" ? "Unpublish" : "Publish"}</button><button type="button" disabled={busy} onClick={() => remove(story)} className="rounded-full border border-red-400/30 px-4 py-2 text-xs uppercase text-red-200">Delete</button></div></form></div></details>)}</div>
  </div>;
}
